name: Build demo site

on:
  push:
    branches:
    - master
    tags:
      - v[0-9]+.*
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.12.0"
          rebar3-version: "3"
      - name: Build
        run: |
          gleam run -m lustre/dev build --outdir=public/priv/static
          mkdir public && cp index.html public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public 
