name: Build Docker Image

on:
  push:
    branches:
    - master
    tags:
      - v[0-9]+.*
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/sammy-ette/somachord:${{ github.head_ref || github.ref_name }} 
